export const GET_TEMP_BY_CITY = "@@weather/GET_TEMP_BY_CITY";
export const GET_TEMP_BY_CITY_REQUEST = `${GET_TEMP_BY_CITY}_REQUEST`;
export const GET_TEMP_BY_CITY_SUCCESS = `${GET_TEMP_BY_CITY}_SUCCESS`;
export const GET_TEMP_BY_CITY_FAILURE = `${GET_TEMP_BY_CITY}_FAILURE`;
